import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import products from "../products.json";

export default function Home() {
  console.log(products);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>The New Electronic Store</h1>

        <p className={styles.description}>Everything In Electronics</p>

        <ul className={styles.grid}>
          {products.map((product) => {
            const { title, image, description, price } = product;
            return (
              <li className={styles.card} key={product.title}>
                <a href="#">
                  <img src={image} alt="led light" />
                  <h2>{title}</h2>
                  <p>
                    <strong>{price} RS</strong>
                  </p>
                  <p>{description}</p>
                </a>
              </li>
            );
          })}
        </ul>
      </main>
    </div>
  );
}
